# Generated by Django 5.2.5 on 2025-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('sslcommerz', 'SSLCommerz')], max_length=50),
        ),
    ]
