# Generated by Django 5.2.5 on 2025-09-05 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_product_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='note',
            field=models.TextField(default=datetime.datetime(2025, 9, 5, 17, 28, 16, 659069, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
