# Generated by Django 5.2.5 on 2025-10-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_color_size_alter_variant_color_alter_variant_size'),
        ('order', '0004_order_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.variant'),
        ),
    ]
